version: 2.1

jobs:
  run-it:
    parameters:
      parallelism:
        type: integer
        default: 1
        description: Number of boxes to use to run this job
    docker:
      - image: cypress/base:10
    parallelism: <<parameters.parallelism>>
    steps:
      - run: echo "runs with parallelism = <<parameters.parallelism>>"

workflows:
  version: 2.1
  main:
    # see how to filter jobs in workflow per branch
    # https://circleci.com/docs/2.0/configuration-reference/#jobs-1
    jobs:
      - run-it:
          name: parallel build job
          # pass parameter to the job
          parallelism: 2
          filters:
            branches:
              # for pull requests do not run this job
              ignore: /pull.*/

      - run-it:
          name: single build job
          # pass parameter to the job
          parallelism: 1
          filters:
            branches:
              # run pull requests with parallelism 1
              only: /pull.*/
